# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/python-starter',
                'doc_host': 'https://moneebullah25.github.io',
                'git_url': 'https://github.com/moneebullah25/python-starter',
                'lib_path': 'python_starter'},
  'syms': {'python_starter.core': {'python_starter.core.foo': ('core.html#foo', 'python_starter/core.py')}}}
