# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/python_nbdev_starter',
                'doc_host': 'https://moneebullah25.github.io',
                'git_url': 'https://github.com/moneebullah25/python_nbdev_starter',
                'lib_path': 'python_nbdev_starter'},
  'syms': {'python_nbdev_starter.core': {'python_nbdev_starter.core.foo': ('core.html#foo', 'python_nbdev_starter/core.py')}}}
